### PR TITLE
use `ruff` instead of `flake8`

### PR DESCRIPTION
**Pull request by zacharyburnett**
use `ruff` in tox env and apply fixes from `ruff --fix drizzle/`

### CODE REVIEW

**Review by mcara — APPROVED** [review]

**Review by mcara — CHANGES_REQUESTED** [review]
Why are the unit tests failing?

**Review by mcara — APPROVED** [review]

**Comment by zacharyburnett** [comment]
> Why are the unit tests failing?

It looks like they haven't been run in 9 months due to lack of activity; perhaps reference files are out of date?

**Comment by mcara** [comment]
I do not see how this PR would make those tests fail. Interesting, it seems like tests didn't run since August of 2022

**Comment by zacharyburnett** [comment]
https://github.com/spacetelescope/drizzle/actions/runs/4578121504/jobs/8084340122?pr=94#step:6:105
```
E           assert 0.05764503023017435 < 1e-06
```
I'm not sure what this is but I assume it could be fixed with updated truths

**Comment by zacharyburnett** [comment]
@mcara it looks like there's an issue for the failing tests: https://github.com/spacetelescope/drizzle/issues/87

**Pull request merged**
