### PR TITLE
Fix devdeps, other updates

### PR DESCRIPTION
**Pull request by pllim**
**Please use "Squash and Merge" button if you decide to merge this!**

I was trying to fix devdeps and went down the rabbit hole of updating everything else to current standards.

Close #97 

Address Windows portion of https://github.com/spacetelescope/drizzle/issues/62

### CODE REVIEW

**Comment by pllim** [comment]
Yeah, your manifest prunes out the test data. The build isolation stuff isn't going to work.

**Comment by pllim** [comment]
Sigh, I ran out of time. Still not sure where this came from. Either editable install mode is refusing to pick up numpy-dev during build or there is real incompatibility in your C-extensions.

Feel free to take over if you want. Most of the diff is generic clean-up, so if you want that in a different PR, lemme know.

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.
```

**Comment by mcara** [comment]
Impressive! Many thanks! One favor, plase: can you, please move `LICENSE` to the root and relete `licenses` directory?

**Comment by mcara** [comment]
and I will think about one more request just to get to 20 commits

**Comment by pllim** [comment]
Maybe @jhunkeler will have ideas if you can get him to review. 😸

**Review by mcara — APPROVED** [review]
wonderful!

**Comment by mcara** [comment]
I felt I needed to steal @jhunkeler brains to review this PR.

**Comment by pllim** [comment]
Fun fact: The job without tox is 3x faster.

**Pull request merged**
