### PR TITLE
[SCSB-121] rename `master` -> `main`

### PR DESCRIPTION
**Pull request by zacharyburnett**
resolves [SCSB-121](https://jira.stsci.edu/browse/SCSB-121)

preparation for branch rename

### CODE REVIEW

**Comment by zacharyburnett** [comment]
Windows builds are failing for some reason

**Comment by mcara** [comment]
> Windows builds are failing for some reason; I do not think that is related to this PR

```
Run pypa/cibuildwheel@v2.16.4
Run actions/setup-python@v5
Installed versions
Run pipx run --python "C:\hostedtoolcache\windows\Python\3.12.1\x64\python.exe" --spec "D:\a\_actions\pypa\cibuildwheel\v2.16.4" cibuildwheel "." --output-dir '"dist"' --config-file '""' --only '""'
  pipx run --python "C:\hostedtoolcache\windows\Python\3.12.1\x64\python.exe" --spec "D:\a\_actions\pypa\cibuildwheel\v2.16.4" cibuildwheel "." --output-dir '"dist"' --config-file '""' --only '""'
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    CIBW_TEST_COMMAND: 
    CIBW_BUILD: cp3*-win_amd64
    CIBW_ARCHS: auto
creating virtual environment...
determining package name from 'D:\\a\\_actions\\pypa\\cibuildwheel\\v2.16.4'...
creating virtual environment...
installing cibuildwheel from spec 'D:\\a\\_actions\\pypa\\cibuildwheel\\v2.16.4'...
Invalid --only='""', must be a build selector with a known platform
Error: Process completed with exit code 1.
```

`Invalid --only='""', must be a build selector with a known platform` I don't know anything about this. Why suddenly this stopped working?

**Comment by zacharyburnett** [comment]
It appears that this is due to an update in the build action `pypa/cibuildwheel` that caused this error in the Windows environment; `pypa/cibuildwheel` released a hotfix just yesterday but that has not yet been propagated to the OpenAstronomy workflow. 

I made a PR here to fix that https://github.com/OpenAstronomy/github-actions-workflows/pull/184; after that is merged and tagged, we can rerun this workflow here and it should be fixed.

**Comment by zacharyburnett** [comment]
In the meantime, however, as this issue is not related to this PR, I think this can be merged

**Review by mcara — APPROVED** [review]

**Pull request merged**
